language: python

sudo: false

addons:
  jwt:
    secure: RGmCXzTsml4OoNEoENJMSQnAY8zDRyrdifFOLFfs/YnUjF0NuOPDYT+W/unJwJN585rTwaxLbIQXOaZuAgK1qjsEJoByJgVuXfTvTrGMpiAXD+8Pu+rjpd7JcWEU5gxf2HyOmrktW80eZcDxiVB6bFvD1oyhnfT+ZUYENV7n/LxDpe6hSUWWS4RguqGe7DBu9h0VXBwMaupX801MXQXzFX4o1HCm9OFdR9H5ddH+AlGpaYpZq+gPFBfkrLju7TMqMOwjaUCK34dbZRbs7dCFkxWwRPKJpbWo5qqTI1VAUXtqruM/l7ZOAmUdU5VzlqHyssPCcjNL3o5UCK1D4kC9KbgT2fXgRSRyo59jLjGCYdW7Z2hbtPDP1UQCblhmaw7CPSPbRdnLTkbtyURN1ItQIc1ZMxh2KhHm2xdGdlLhgNx4lUz62Bh3jiNxm3g06qS0mjggBvijCRQEPywE4wTbcYjIuVm9U3KrqPpKtytCZ9zNKYbEUasEAarU91wiHMnlbHxuw5gEuwyCaX5sgEnUcThYjNm5/panAFP8hbww8BqtODNbClix6AbHJwSWH9G4vCsoBWCoaeVTMR9JVqk88EPuY1CRhj9PBbB/k8SdREW/+P0nYKemabQFUD1RJAelCLl9YDDPYJxSGSrRREMAnqK6l8QrFYejBZ1hGsNLAkE=

script:
  - echo $SAUCE_ACCESS_KEY