language: node_js
sudo: false
node_js:
  - 0.10

before_script:
  - npm install -g bower
  - bower install
env:
  - SAUCE_USERNAME=platanus


addons:
  sauce_connect: true
  jwt:
    secure: "g6sOQ8prwIh43ZJ97IJkTchpuNcngFuAuhas3mjivWE2OVo2DfxCVWDmGcMmwh56lJ9V91EfpE2k0rCd8XTRijhDV0/zVOzS9p0xLc53lwSgbtVDyrAiqTQX5KRXeLQwsKA3hXgNt9tY3qo2HdUqfe3oSJIhfnuSDb57tKCi7F9RQGzy7a4hVis4IC6PKnsEW9D65HXPUskM96BJn3ZmCn7A9ARSpnY96ZVQIeZDwl+b0UH58mLsug2HrVTQHIBllQj7Ppi4pWsUTlw3ynXfftV33FKuCXbgVVEcoeRL5GgD23u7lq85NpA6tEmA7CzwLp3GJ6ngOUXAN0/mtfaiRuokcodjNC5V0GsgbBBDlgXwKGRXrr8NH82tbRjPZRISXO0ZV5WGfthpj09lXyTYHLuU0XjMt6LccgSkUL0DF12twVmLkWO2b0bA+qwwsq6UVwsPIduwQA6L4kxrKGdoVEZMs1GzVOonK1EW/uRjUnlj6kGN8ogPWRjujKkiQshOo0+/4NYoT/0Au3GnocC4M3uFy/iQ6nqC+gIhVJXy0w0ndAZ8xKAt3RHgPKJjRMJ0BCbVn/LToSXdQB2V8HQaCfXmsOWVjTE/TKzfdVwKaJZWU2QosRbPSGCwwq6tlgdu4nKd5WCR5ZSWhmeP0lp/8q3O5jh0RG/dXF0zPo8F1rE="