language: node_js
sudo: false
node_js:
  - 0.10

before_script:
  - npm install -g bower
  - bower install
env:
  - SAUCE_USERNAME=platanus


addons:
  sauce_connect: true
  jwt:
    secure: "mL0EqMialniSxn0g/XasAMu3vJ56MtXSO8O4onuL7fQTXd/m523BnN3IWNGFqw60YIjddUH6FHUDgPXI40IswS/CrCvG6t4hi900Ztm9+ozimZozMevkniJOYWO28+zVo2QWBdlIq3v5w+8gRRMBOR3N31tPNp2xlztrQ/MopJz9f0DvgtEPY7PhS707BOd2fXxCPfZ4VELqotGY1SMgheuh2cLIddFguMKy0OAge401JH4Fjw+le3f6pMRLftIx4gXAdSvlM8F+EbyMBvCKA5sM215CjFBnjSmr+02syaFWUxGJ0GjGnbx38QgbXGxWs0CN0mwe4ULsIFlKXBsRBrSeaqOaDK4tJAewrihN1IeD/lUKfdugdWNDf5cpaKEIQvft63VpSP5rTOkj9BWzr0l5fzkeCcIzd6VVVA30q0O6KvGqytxpHmcefecHafAyFhUU3o+jAlREYUq8waIDN2RrXGFYcrHZwHXn+vHHxeJnezIwcATJnutnc265E3jOuJvL9hnJuI7OXrZ8V4jojdxYifI8DpKbkXEr4ZV0YJ3xzhCcsF9LIWa5+ZkVQk3Y1FIu0ng3Ns2eGHXvtlIKAlEPv+FZq3JY9h0Y85WwJo3UaNPEVbpOA9udt6wIcoAaZwG1iY0uvUp41v1MVNByy3R2wxf3viX81vZoacZUM8Y="