language: ruby
rvm:
 - 2.2
addons:
  jwt:
    secure: UgsMsvsTG/stHJDyah0YHHFwz9wtLNzqg9tXEpc99BspIm8oZ1nD9P+HMIu5hcPJJpM22xLnIDgslNARdBcXPPGuxSI0RFRhJKE7CeOwzOeEIjxPJzdNXGrkh9g7V2kCs/bcYc952Lmk8IY9Yl12KqLmgtwwvsu/f//y2Enawj6qMr8bC8ITyUtQxxLw7UHEzH8ft+IX2MwJNm3ILUpN0cqTYF7mMVmqAsH7ZIpXxnL5VCM4DhhzO1cqJ5CsYIAWokEPc7t+054M/E+M12X/SbeEU4jOlIsKTTRJGZk7Jl/9hzqeb00nRLI6k504P1QjzkKs5orRu9YaYdLXkR+edDhRBhTD2XL/Ded5rbb58F1j+8PObhnuIBggueQtqNPnE2w+0d2TZnCf0pplDv1cL44rGjGjkVrR99gcgVj9T/95ixI1SU9WcrSpCrawjlEYYU5JtiWZA/eyr4eY3Oe/I7BmpAMwYHynqp74EbBEVgWGMMKmbwJcUMiL2KMdVQXzUw8D/pTrGaE8MfZ7ehU/yXksFmeIR9QoXzdtj1/jKfd29ZWqvE9CDQglSb9o6nSkAtNWDguW732tzUHJ+cejn6SVLHk2vyVADEUEjsesL/pBHGdYrXDzIQFE0WFuJKtQk5kb4pY6+KCIwsLCSiiTn2Q64nDNSujP7wWRbBnz9zI=
