language: python

sudo: false

addons:
  jwt:
    secure: "nbLK8H7ikY+SaXxCbgIozb8GDZMDqlEprssQhs1C3rhbY1HFJOxSFGpQVz2VuZoXuSEH/WrVjADqVrZuve4EJ/Hl9UpSEASDhnbfegKCnaMs6h+FAncQfKaKgQlLtCJbIAUTa0XcDha00LYkVxe9G7emhTc34K5XBUi1uI2IeZ50IKu4y4vg9I4mjFg0zz2VgciadYguskjhE6kwMZkuDcK8bs1GeaOPgTbuvZZhu8zFyRg+N+ojwwb2S8/cFefvGKT0hwKpQqbSXRhNVLx9xZR68eFX8UH1a9EYWpjTYDjSwKLAkQM5HVmXIE004bjrv5dkoYQRC9WLDTuTZPgKksrWg4alYWmMRn9Y8k3v36qg+fjs45Wlq8XK11nSa2XWbls+ZQYLitgXMY2JvmvKW+E2gXGqG9kVfCQfF18+I/NocGx7djWwNZOJb49Dwult/zWf0xr+nyj4nH4Nc8OHAZt3P6z9DdNPsvIxUU00ar/41cF0GsA0QBhHYCpd2Tc4X4uco2dfpu27bElSfyGuJC2I1/hHH5xQ37PKir2iJ2qUWy4BXC+c1HOCHFXghJJqYk5rWIqOAW/a8giahv20Q0/GuP0m0CZxdgQ9035mxRVuz+3yJBXeELC1GQPCXFtd0t7dDTmM6j9WRD2wacs6E8t/CKGdDWqcLVnSVUxw8sQ="

install:
  - true

script:
  - echo $SAUCE_ACCESS_KEY