language: node_js
sudo: false
node_js:
- 0.1

env:
- SAUCE_USERNAME=platanus

addons:
  jwt:
    secure: cjeaCtwNZtTYXQ34LlADFkrquDAvLF8sxf3rGjVusDvF2fZgH5HgIPn21QDiOEu7J/b8TMe1yacRFdcWAa+kmGz/ofhqPyjaNrASN9bTmr5r6pFh5hxwoC1TdB8Y8Bz3CXAi6wT0HIxOgyVjRSmQxfZEnXD2ePpNRLfokwgHj7BRjvpgZhrUGINBecqTVs65hr8/e2D/KA97dx/kvzjIr1j1a7t6gUPHqyTX4PlJaJFtASzESPSE9IvDi2CsZNgmnqgldf2b22Oc1CxfMADrSuYnU567mrIb6br5bEuPNRKtvO5/AguKu0dV9oQ8W79lNZXK5wwDIkGNkHDNeTKSv2XtuD28vlLdqii46ojyIzIk4EB2dpzFwqrInkSNHjmyuLpVo3Uz/IZl/aAYm+1nBlGJltD3dnLhtZedA0HnI72Wt30Yo5FpAcDOakNQO7b2c3ZTJ2pqiW1nuVFhv+HOUspzTSkaEuYld/HVIHWlFS5LBlvSF6qg/dVR91lBLih3+vZia9r0BInUcaNVZik9ByzxJqIQv/M0LhDLHOmnCBqV6rWmLY2pDQNgtJxa+qMSgkFMTxkE1CIb8vfHcnc5oQ74CUZnQ2XGj0i3+hqEgMYselWp0QxPT41Hi5gS1ITWwKPLEiWiWZMbPldX5/Sx4tIBotRSrp/l0aZdS6My19o=

script:
  - env
