language: ruby

install:
  - true

script:
  - true

addons:
  jwt:
     saucelabs:
        secure: HdEeAwLz6LLg5frjX3wOgfyF+65A4c3RLvDzHlRWON4eEuyYRX2Qj0ZBXDFvnnNLi0MsR9MAM6sUugn4DGkQB1HcTa7U1w1KyCJKbAC5yaMavLiuTYfa6Kyz9TSmHsYD5aW3jakjMw5hwa0cFDSjQNl3wYqpGpZ0VVLtq5SK6rZ/Oo7gDCkmCxzqIghxbdQUstoq5/6wihAmWB2OawYNQplcZ2xlB172XkirnfI9F/3yuKN/yBv9BWGp/WRHSwcbGgOF3Qlho5Db00sCe109q1t3Cg5b8sp1TMK2spYdXXUYoBb7t/KnWRdOevufTeQ7rStn3fACm7TxfJcNxKkziK4na48AAjxPvWc8xawtKItiyWf6W61iofn2IItXTYPDckbXnDEiDoUb0nBcc2mreePKIWWdMj61p94YxX1UsoSKawuOyKClssoSSax9k3qQuMXYIkCLLRxo6zsZNeRCIjdFz1ug79sS1u8ctaC+34+Xoe7lbQTnBzWKYg8UBVygGvYE4aip7rwwOuluBaXUSH2pdoGEXiXuC2V7YLmSJqtnzIngw4GksgcszgIj1IRXgcImV0i+R4ml872pfdb6J18pj96rlmO5Dy74s0xuelanTQPnFlbwOn1qwrIqQ2u3Y0SI77M8OXaTEDMELwBChFC+SqfuU77fxgNpQEEFduM=