language: python

sudo: false

addons:
  jwt:
    saucelabs:
      secure: "N6vucXdgkH6uQoHNb2mT0kiX4hPJfQeLyzCepcCDX2MhDL7ImLnDaEwHqRJgBX/qH+YFCTg3uhMz4sBkQziXU3TCMmIkMmr8TN/cieubTwhm9YbeQylsK8B2RwbVSOFhWdZzwt0uejU9vfV5gapZggC0v5vTUsr3MaeA6jhMPimjd66SgXCiMtCwSjhtecHwMJfb0fqxpdLtOnVMjmUfxi6d1N2/9qnF57HFQ48aDT0GO1KKX85XIqTEyAt+iFn82MUt+KrinjHuikVhizVFlKPuQaKVWdxygGt+d6H1gBsisC3Dwck5SooSiVdlnFKB1izH45Q6FZMpWbkV4KgSr0d/hHq0C3hj2RsqMgKKzzgt47MU+vMSTz1nnoRqwaZacT7G9TaLZU4vl37FwbKXTl4yNoW1TsZQlVd/q2QWjrL/i+qMoq/J1Zrp+SFlgdaqlXwqbU3WOrlIJ/oZopjfBrvTX9l5ebZY/yZheQ8MByIN6SxGMZg7CxU0Q26/rRgvduld/9n2FTI8metgYgN9Pq5G1S8X5cS2Vx3zNXWRMfelGjzwLcQWlTGKpvpXe4XAyNHHZn7A/jCYUdNgAuWFrM/4lEhJLMRg+fRZ5LKA940Rx7dARXm8qBIIrqrKd7GLVyjALfBpaxhd2wxF7zDU7Ta1xmMVK1aaIMaBASizrFQ="

install:
  - true

script:
  - echo $SAUCE_ACCESS_KEY